<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Classlist_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get classlist by classListID
     */
    function get_classlist($classListID)
    {
        return $this->db->get_where('classlist',array('classListID'=>$classListID))->row_array();
    }
    
    /*
     * Get all classlist count
     */
    function get_all_classlist_count()
    {
        $this->db->from('classlist');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all classlist
     */
    function get_all_classlist($params = array())
    {
        $this->db->order_by('classListID', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('classlist')->result_array();
    }
        
    /*
     * function to add new classlist
     */
    function add_classlist($params)
    {
        $this->db->insert('classlist',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update classlist
     */
    function update_classlist($classListID,$params)
    {
        $this->db->where('classListID',$classListID);
        return $this->db->update('classlist',$params);
    }
    
    /*
     * function to delete classlist
     */
    function delete_classlist($classListID)
    {
        return $this->db->delete('classlist',array('classListID'=>$classListID));
    }

    function getclass($params = array())
    {
        $this->db->order_by('classListID', 'desc');
        $this->db->where('classID', 0);
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('classlist')->result_array();
    }

    public function showAllClasses(){
        $this->db->select('c.*, CONCAT(u.userFN, " ", u.userLN) AS userName');
        $this->db->from('classlist as c');
        $this->db->where('c.classID', 0);
        $this->db->join('users as u', 'c.studentID = u.userIDNo', 'LEFT');
        $this->db->order_by('userName', 'asc');
        $query = $this->db->get();
		if($query->num_rows() > 0){
			return $query->result();
		}else{
			return false;
		}
	}
}
