<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get user by userID
     */
    function get_user($userID)
    {
        return $this->db->get_where('users',array('userID'=>$userID))->row_array();
    }
        
    /*
     * Get all users
     */
    function get_all_users()
    {
        $this->db->order_by('userID', 'asc');
        return $this->db->get('users')->result_array();
    }
        
    /*
     * function to add new user
     */
    function add_user($params)
    {
        $this->db->insert('users',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update user
     */
    function update_user($userID,$params)
    {
        $this->db->where('userID',$userID);
        return $this->db->update('users',$params);
    }
    
    /*
     * function to delete user
     */
    function delete_user($userID)
    {
        $this->db->where('userID',$userID);
        return $this->db->update('users',$params);
    }
}
